language: cpp

sudo: enabled

compiler:
  - gcc

matrix:
  include:
    - name: CUDA 11
      env:
        - CUDA=11-0-local_11.0.1-450.36.06-1
        - CUDA_SHORT=11.0.1
        - UBUNTU_VERSION=ubuntu1804
      dist: bionic

before_install:
  - |
    INSTALLER=cuda-repo-${UBUNTU_VERSION}-${CUDA}_amd64.deb
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
    sudo mv cuda-${UBUNTU_VERSION}.pin /etc/apt/preferences.d/cuda-repository-pin-600
    wget http://developer.download.nvidia.com/compute/cuda/${CUDA_SHORT}/local_installers/${INSTALLER}
    sudo dpkg -i ${INSTALLER}
    sudo apt-key add /var/cuda-repo-${UBUNTU_VERSION}-11-0-local/7fa2af80.pub
    sudo apt-get update -qq
    sudo apt-get -y install cuda
